title: Julio Rodrigues
email: juliorodriguesfe@hotmail.com
description: >-
Data Analyst | SQL, Python, R, Power BI, Tableau
Turning data into actionable insights.


baseurl: ""
url: "https://github.com/juliorodrigues97/portfolio"


theme: minima


linkedin_username: https://www.linkedin.com/in/julio-cesar-rodrigues/
github_username: https://github.com/juliorodrigues97

