title: Julio Rodrigues
logo: <img src="https://github.com/juliorodrigues97/portfolio/blob/main/assets/000095900004.jpg?raw=true" alt="Profile Logo" style="border-radius: 50%; width: 150px;">
description: Data Analyst
#show_downloads: true
theme: jekyll-theme-minimal
