title: Julio Rodrigues
logo: <img src="000095900004.jpg" alt="Profile Logo" style="border-radius: 50%; width: 150px;">
description: Data Analyst
#show_downloads: true
theme: jekyll-theme-minimal
css: assets/css/styles.css
markdown: kramdown
